services:
  accounts:
    image: victorqueirogabr/accounts:s4
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  loans:
    image: victorqueirogabr/loans:s4
    container_name: loans-ms
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank
  cards:
    image: victorqueirogabr/cards:s4
    container_name: cards-ms
    ports:
      - "8089:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - easybank

networks:
  easybank:
    driver: bridge