spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Accounts service"
  contactDetails:
    name: "Queiroga victor"
    email: "contato2@victorqueiroga.com"
  onCallSupport:
    -(555) 555-5555,
    -(555) 555-5556